Task 1 2 1
y-primakova/OOP pull request #3
Opened 2023-10-19 16:51 UTC by y-primakova

2023-10-21 14:54 UTC, BIGNIKi commented
PR назвала не правильно, из-за этого авто тесты и check style не запустились

2023-10-21 15:16 UTC, BIGNIKi requested changes

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/IteratorBFS.java
> +    public boolean hasNext() {
Кидать исключение ConcurrentModificationException. Разобраться, когда это нужно делать.

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/IteratorBFS.java
> +        return null;
Итератор никогда не должен возвращать null. next всегда возвращает элемент итерирумого объекта.
Когда элементы кончились, он должен кидать NoSuchElementException.
https://javarush.com/groups/posts/1884-pattern-iterator

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/IteratorDFS.java
> +public class IteratorDFS<T> implements Iterator<T> {
Здесь все ошибки аналогичны, как и в BFS итераторе

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Main.java
> +        while (bfs.hasNext()) {
Сделай в Tree метод toString, чтобы было удобно выводить дерево на консоль

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Tree.java
> +    public Tree<T> addChild (T value){
А если передали null в качестве value? Имеет какой-то смысл создавать ноду дерева, где хранится null?
Сделай свой класс исключения и кидай его в этом случае

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Tree.java
> +    public void addChild (Tree<T> subtree){
Здесь аналогично - что если null?

2023-10-21 15:16 UTC, BIGNIKi commented on Task_1_2_1/src/test/java/ru/nsu/primakova/TreeTest.java
> +    public void TestBFS(){
Класс TreeTest должен тестировать только Tree.
Для итераторов отдельные тестовые классы создай. Это нужно, чтобы: не перегружать один тестовый класс и разграничивать тестируемые сущности по разным тестовым классам.

2023-10-21 15:24 UTC, BIGNIKi requested changes

2023-10-21 15:24 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Tree.java
> +public class Tree<T> {
Удаление поддеревьев не добавила.

2023-10-21 15:24 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Tree.java
> +            if(bfs1.next() != bfs2.next()){
Тут ошибка. Т.к. проверяешь ссылки. А если создали два дерева разных: A -> B и A -> B? У элементов A, B из первого дерева ссылки будут отличаться от ссылок A, B из второго дерева.
Надо значения проверять.

2023-10-25 04:43 UTC, y-primakova commented
Я не все правки сделала, но решила пока что есть отправить, чтобы потом меньше проверять осталось

2023-10-25 08:34 UTC, BIGNIKi requested changes

2023-10-25 08:34 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Tree.java
> +public class Tree<T> {
Получается, не поддеревьев, а элементов. Поддерево у тебя уже удаляется через remove.

2023-10-26 08:38 UTC, BIGNIKi requested changes

2023-10-26 08:38 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/IteratorBfs.java
> +        if (this.length != startTree.get_length()) {
Условие не проверяет, что дерево изменилось

2023-10-26 08:38 UTC, BIGNIKi commented on Task_1_2_1/src/test/java/ru/nsu/primakova/IteratorDfsTest.java
> +            while (dfs.hasNext()) {
Написать тесты на foreach для Tree

2023-10-26 08:38 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/ru/nsu/primakova/Tree.java
> +public class Tree<T> {
Реализовать стандартный механизм итерации

2023-10-26 08:39 UTC, BIGNIKi commented
Если 26.10 доделаешь, то hard дедлайн сдан.
На паре защитила

2023-10-26 14:54 UTC, BIGNIKi approved these changes

2023-10-28 11:07 UTC, merged