Task_1_3_1
y-primakova/OOP pull request #5
Opened 2023-11-16 05:36 UTC by y-primakova

2023-11-16 07:59 UTC, BIGNIKi requested changes

2023-11-16 07:59 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/ru/nsu/primakova/SubstringSearch.java
> +        reader.close();
Через try with resources сделать

2023-11-16 07:59 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/ru/nsu/primakova/SubstringSearch.java
> +        var reader = new BufferedReader(new InputStreamReader(new FileInputStream(filename), StandardCharsets.UTF_8));
Давай еще сделаешь чтение файла из ресурсов. Полезно будет разобраться, что такое ресурсы в джаве, где ждет их gradle и что gradle с ними делает при сборке.

2023-11-16 07:59 UTC, BIGNIKi commented on Task_1_3_1/src/test/java/ru/nsu/primakova/TestSubstringSearch.java
> +public class TestSubstringSearch {
Сделай еще тестовый метод, который генерит большой файл (15-20 гигов), ищет в нем подстроку (какую-нибудь небольшую, которая находится в самом конце файла). Также программно удалить этот файл. (как junit тест его не делай, кто знает как на это github workflow отреагирует)

2023-11-19 08:34 UTC, BIGNIKi approved these changes

2023-11-19 08:34 UTC, BIGNIKi commented on Task_1_3_1/src/test/java/ru/nsu/primakova/TestSubstringSearch.java
> +    public void testBigFile() {
Запускала тест на этом файле? Долго работал?
Можно потом на паре показать.

2023-11-19 09:28 UTC, y-primakova commented on Task_1_3_1/src/test/java/ru/nsu/primakova/TestSubstringSearch.java
> +    public void testBigFile() {
Да, запускала. На 9 гб работал около трех минут

2023-11-23 15:28 UTC, merged